### ISSUE TITLE
Hope to add a new simplified Chinese language

### ISSUE THREAD

**Issue by katelya77** [PasteBar/PasteBarApp#129]
I like your project very much, but limited to my English level is not enough, it is not very convenient to use your software, and many of my friends I recommend them to use more speaking great, but there is no language that we are suitable for, I hope you can come out with a Chinese language, thank you！

**Comment by kurdin** [comment]
@katelya77 I'll can add any language using automatic translations tool but I'll need a help from native speakers to improve the final translations and make sure it look good in UI. @katelya77 if you don't mind, I'll reach out to you when I'll have something available for Chinese language. 

Thank you very much!

**Comment by kurdin** [comment]
@katelya77  could you please look at 
https://github.com/PasteBar/pastebar-localization/tree/main/zh-CN
and help to improve translation for Simplified Chinese Language. Thank you.

**Comment by katelya77** [comment]
> @katelya77 could you please look at你能看看吗 https://github.com/PasteBar/pastebar-localization/tree/main/zh-CN and help to improve translation for Simplified Chinese Language. Thank you.并帮助改进简体中文的翻译。谢谢。

Of course, I would be more than delighted to assist you.

**Comment by katelya77** [comment]
> @katelya77 could you please look at https://github.com/PasteBar/pastebar-localization/tree/main/zh-CN and help to improve translation for Simplified Chinese Language. Thank you.
I have completed the revisions related to the Chinese content in your project.

**Comment by kurdin** [comment]
@katelya77  Thank you very much for your contribution. 
Is this translation Ok 
```
zh-CN:
  add_first_item_here: 在此添加第一个项目
  disable_history_capture: 禁用历史记录捕获
  enable_history_capture: 启用历史记录捕获
  clipboard_image_size: 剪贴板图像大小
  history_capture_is_disabled: 剪贴板历史记录捕获已禁用
  recent_history: 最近历史记录
  open_pastebar: 打开 PasteBar
  unlock_pastebar: 解锁 PasteBar
  quit: 退出
  ```
  in https://github.com/PasteBar/pastebar-localization/blob/main/services/translations/translations.yaml ?
